#!/usr/bin/php
<?php

use ZXC\ZXCConfig;
use ZXC\ZXCFactory;
use ZXC\Native\Modules;
use App\Modules\DbMigration\DbMigration;

require dirname(__FILE__) . '/../../vendor/autoload.php';

$config = ZXCConfig::create(dirname(__FILE__) . '/../../config/');
ZXCFactory::create($config);

/** @var DbMigration $migration */
$migration = Modules::get('DbMigration');

$migration->setEnvironment(
    dirname(__FILE__),
    $config['modules']['DB']['options']['dsn']
);

if (in_array('--create', $argv)) {
    $migration->createDatabase();
}
if (in_array('--update', $argv)) {
    $migration->update();
}
