<template>
    <v-dialog
        v-model="dialog"
        :width="dialogWidth"
        :fullscreen="$vuetify.breakpoint.xs"
        persistent
        scrollable
    >
        <v-card
            width="100%"
        >
            <v-toolbar
                elevation="1"
            >
                <v-toolbar-title>
                    {{ $t( 'task.task' ) }}
                </v-toolbar-title>
                <v-spacer />
                <v-btn
                    v-bind="closeBtnParams"
                    @click="goBack"
                >
                    <v-icon>
                        mdi-close
                    </v-icon>
                </v-btn>
            </v-toolbar>
            <app-progress
                :class="loading ? 'ma-5' : ''"
                :loading-active="loading"
            />
            <v-card-text
                v-if="!loading"
                style="height: 100%;"
                class="pt-4"
            >
                <v-row>
                    <v-col
                        cols="12"
                    >
                        <task
                            :task="detailedTask"
                            :restricted-mode="true"
                        />
                    </v-col>
                    <v-col
                        cols="12"
                        class="pa-0 pl-15"
                    >
                        <task-priority
                            :task="detailedTask"
                            :currently-selected="detailedTask.priorityId"
                        />
                    </v-col>
                    <v-col>
                        <task-tags
                            :task="detailedTask"
                        />
                    </v-col>
                    <v-col
                        cols="12"
                    >
                        <v-card
                            elevation="1"
                        >
                            <v-card-text>
                                <task-note
                                    :note="detailedTask.note"
                                    :task-id="detailedTask.id"
                                    :can-edit="canEditTaskNote"
                                />
                            </v-card-text>
                        </v-card>
                    </v-col>
                    <v-col
                        cols="12"
                    >
                        <v-card>
                            <v-card-text>
                                <task-deadline
                                    :deadline="detailedTask.deadline"
                                    :task-id="detailedTask.id"
                                    :can-edit="canEditDeadline"
                                />
                            </v-card-text>
                        </v-card>
                    </v-col>
                </v-row>
            </v-card-text>
            <v-card-actions>
                <action-move-task
                    :task-id="detailedTask.id"
                />
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>

<script src=./TaskDetails.ts />
